### ISSUE TITLE
terrainRuler is not defined

### ISSUE THREAD

**Issue by crymic** [manuelVo/foundryvtt-terrain-ruler#30]
On Version 9 269
DND5e 1.6.3
Libwrapper 1.12.7.0
Drag Ruler 1.12.8

When dragging a token, I do not get a ruler anymore.. However I do get these errors.
```
libWrapper-wrapper.js:673 
        
       Uncaught ReferenceError: terrainRuler is not defined
[Detected 2 packages: drag-ruler, lib-wrapper]
    at measureDistances (compatibility.js:33:27)
    at DragRulerRuler.measure (foundry_imports.js:254:20)
    at DragRulerRuler.measure (ruler.js:69:20)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:139:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:131:22)
    at Token5e.onEntityLeftDragMove (main.js:139:15)
    at Token5e.onEntityLeftDragMoveSnap (main.js:132:23)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:1649:92)
    at MouseInteractionManager._handleDragMove (foundry.js:1668:158)
    at MouseInteractionManager._handleMouseMove (foundry.js:1666:18)
    at a.emit (index.js:202:33)
    at r.dispatchEvent (interaction.min.js:8:12018)
    at r.processPointerMove (interaction.min.js:8:16963)
    at t.recursiveFindHit (interaction.min.js:8:3973)
    at t.findHit (interaction.min.js:8:4032)
    at r.processInteractive (interaction.min.js:8:12624)
    at r.onPointerMove (interaction.min.js:8:16395)
measureDistances @ compatibility.js:33
measure @ foundry_imports.js:254
measure @ ruler.js:69
scheduleMeasurement @ foundry_imports.js:139
onMouseMove @ foundry_imports.js:131
onEntityLeftDragMove @ main.js:139
onEntityLeftDragMoveSnap @ main.js:132
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁Token.prototype._onDragLeftMove#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:1649
_handleDragMove @ foundry.js:1668
_handleMouseMove @ foundry.js:1666
a.emit @ index.js:202
r.dispatchEvent @ interaction.min.js:8
r.processPointerMove @ interaction.min.js:8
t.recursiveFindHit @ interaction.min.js:8
t.findHit @ interaction.min.js:8
r.processInteractive @ interaction.min.js:8
r.onPointerMove @ interaction.min.js:8
compatibility.js:33 
```
```     
       Uncaught (in promise) ReferenceError: terrainRuler is not defined
[Detected 3 packages: drag-ruler, lib-wrapper, enhanced-terrain-layer]
    at measureDistances (compatibility.js:33:27)
    at DragRulerRuler.measure (foundry_imports.js:254:20)
    at DragRulerRuler.measure (ruler.js:69:20)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:139:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:131:22)
    at onEntityDragLeftDrop (main.js:156:15)
    at 🎁Token.prototype._onDragLeftDrop#drag-ruler (main.js:83:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at Token5e.onDragLeftDrop (terrain-main.js:373:3)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁Token.prototype._onDragLeftDrop#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:1649:92)
    at MouseInteractionManager._handleDragDrop (foundry.js:1672:336)
    at MouseInteractionManager._handleMouseUp (foundry.js:1669:144)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.js:8:12018)
    at r.processPointerUp (interaction.min.js:8:15603)
    at t.recursiveFindHit (interaction.min.js:8:3973)
    at t.recursiveFindHit (interaction.min.js:8:3757)
    at t.recursiveFindHit (interaction.min.js:8:3757)
    at t.recursiveFindHit (interaction.min.js:8:3757)
    at t.recursiveFindHit (interaction.min.js:8:3757)
    at t.findHit (interaction.min.js:8:4032)
    at r.processInteractive (interaction.min.js:8:12624)
    at r.onPointerComplete (interaction.min.js:8:14355)
    at r.onPointerUp (interaction.min.js:8:15172)
    ```

**Comment by manuelVo** [comment]
Which Version of Terrain Ruler do you have installed?

**Comment by crymic** [comment]
1.6.0

**Comment by manuelVo** [comment]
Do you have any other modules except Drag Ruler, Terrain Ruler, Enhanced Terrain Layer and socketlib installed? If so, please disable all modules except those listed above and see if that makes the ruler appear again. This information helps to diagnose any possible module conflicts.

**Comment by crymic** [comment]
I rebooted my server the other day, the error went a way it looks like.
Some cache issue I guess was the problem.
